
on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: "PRINT FILES befor"
        run: ls
      - uses: actions/checkout@v3
      - name: "PRINT FILES after"
        run: ls